### ISSUE TITLE
[feat] : 사용자는 예매대기로 부터 알림을 받으면 6시간동안 예매 예매를 진행할 수 있다

### ISSUE THREAD

**Issue by EunChanNam** [dev-hooon/interpark#37]
## 🔨 Describe
* 스케줄러를 통한 예매대기 처리 프로세스 구현

## ✅ Tasks
- [x] 에매대기 처리 스케줄러 구현
- [x] 예매대기 활성 후 6시간동안 예매를 안하면 좌석을 예매가능으로 처리하고 예매대기를 종료시키는 스케줄러 구현
- [x] 이메일 발송 이벤트 구현
- [x] shedlock 설정
